name: TEST2
on: 
  pull_request:
    types: [opened, synchronize]
  


jobs:
  check-permission:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls

      - name: echo
        run: echo >>>${{ secrets.NPM_PRIVATE_REGISTRY_EMAIL }}<<<
