name: Build and Test Workflow
on: 
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      FVT_APIML_ARTIFACT:
        description: 'APIML build for integration test'
        required: true
        default: 'libs-release-local/org/zowe/apiml/sdk/zowe-install/*/zowe-install-*.zip'
      FVT_API_ARTIFACT:
        description: 'Jobs API artifact download pattern'
        required: true
        default: 'libs-snapshot-local/org/zowe/explorer/jobs/*/jobs-api-package-*.zip'
      FVT_ZOSMF_HOST:
        description: 'z/OSMF server for integration test'
        required: true
        default: 'zzow01.zowe.marist.cloud'
      FVT_ZOSMF_PORT:
        description: 'z/OSMF port for integration test'
        required: true
        default: '10443'
      FVT_SERVER_HOSTNAME:
        description: 'Server hostname for integration test'
        required: true
        default: 'fvt-test-server'
      API_ML_DEBUG_PROFILES:
        description: 'Debug profiles for API Gateway'
        required: true
        default: 'default'


jobs:
  check-permission:
    runs-on: macos-latest
    steps:
      # this action will fail the whole workflow if permission check fails
      - name: check permission
        uses: zowe-actions/global-setup/permission-check@main
        with:
          user: ${{ github.actor }}
          github-repo: ${{ github.repository }}
          github-user: ${{ secrets.ZOWE_ROBOT_USER }}
          github-passwd: ${{ secrets.ZOWE_ROBOT_TOKEN }}

  setup-build:
    runs-on: macos-latest
    needs: check-permission
    steps: 
      # Initial setting up environments
      - uses: actions/checkout@v2

      # Cache .npm
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ~/.nvm/.cache
            ~/.nvm/versions
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-cache-node-modules-
      
      - uses: zowe-actions/global-setup/envvars-global@main
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
      - uses: zowe-actions/global-setup/generic-setup@main
        # with:
        #   extra-init: |
        #     console.log('1234')
        #     console.log('5678') 
       
      # Set up NodeJS env
      - name: Nodejs project setup action
        uses: zowe-actions/nodejs-actions/setup-action@main
        with:
          package-name: 'org.zowe.explorer-jes'
          nodejs-version: 'v10.18.1'
          install-registry-url: ${{ env.DEFAULT_NPM_PRIVATE_INSTALL_REGISTRY }}
          install-registry-email: ${{ secrets.NPM_PRIVATE_REGISTRY_EMAIL }}
          install-registry-username: ${{ secrets.NPM_PRIVATE_REGISTRY_USERNAME }}
          install-registry-password: ${{ secrets.NPM_PRIVATE_REGISTRY_PASSWORD }}
          publish-registry-email: ${{ secrets.NPM_PRIVATE_REGISTRY_EMAIL }}
          publish-registry-username: ${{ secrets.NPM_PRIVATE_REGISTRY_USERNAME }}
          publish-registry-password: ${{ secrets.NPM_PRIVATE_REGISTRY_PASSWORD }}

      # Build project
      - name: Nodejs project build 
        run: |
          set +x
          . $HOME/.nvm/nvm.sh
          nvm use v10.18.1
          set -x
          npm run prod

      # Unit test
      - name: Nodejs project unit test 
        run: |
          set +x
          . $HOME/.nvm/nvm.sh
          nvm use v10.18.1
          set -x
          npm run test

      # Integration test
      - name: Integration test
        timeout-minutes: 30
        run: |
          echo "Preparing server for integration test ..."
          ./bin/prepare-fvt.sh "${{ github.event.inputs.FVT_APIML_ARTIFACT }}" "${{ github.event.inputs.FVT_API_ARTIFACT }}" "${{ github.event.inputs.FVT_ZOSMF_HOST }}" "${{ github.event.inputs.FVT_ZOSMF_PORT }}"
          sleep 120
          ZOWE_USERNAME=${{ secrets.SSH_MARIST1_USERNAMEP }}
          ZOWE_PASSWORD=${{ secrets.SSH_MARIST1_PASSWORDP }}
          ./bin/delete-fvt-jobs.sh
          echo "Starting integration test ..."
          SERVER_HOST_NAME=${{ github.event.inputs.FVT_SERVER_HOSTNAME }}
          SERVER_HTTPS_PORT=7554 
          TEST_BROWSER=firefox
          npm run test:fvt
          find .fvt/logs -type f | xargs -i sh -c 'echo \">>>>>>>>>>>>>>>>>>>>>>>> {} >>>>>>>>>>>>>>>>>>>>>>>\" && cat {}'

      
# to access inputs, call ${{ github.event.inputs.SOMETHING }}