name: TEST
on: 
  pull_request_target:
    types: [opened, synchronize]
  


jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls

      - name: echo
        run: echo >>>${{ secrets.NPM_PRIVATE_REGISTRY_EMAIL }}<<<

