name: Codescan Workflow
on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  run-audit:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

<<<<<<< HEAD
<<<<<<< HEAD
      - name: Prepare workflow
        uses: zowe-actions/shared-actions/prepare-workflow@main
=======
      - name: Apply Global Environment Variables
        uses: zowe-actions/shared-actions/envvars-global@main
>>>>>>> dea76e7 (Update shared actions path)
=======
      - name: Prepare workflow
        uses: zowe-actions/shared-actions/prepare-workflow@main
>>>>>>> 8b5f64d (Debug nodejs setup action)
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: Install
        run: npm install --no-audit

      - name: Audit
        run: npm audit --prod

  run-lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
<<<<<<< HEAD
<<<<<<< HEAD
      - name: Prepare workflow
        uses: zowe-actions/shared-actions/prepare-workflow@main
=======
      - name: Apply Global Environment Variables
        uses: zowe-actions/shared-actions/envvars-global@main
>>>>>>> dea76e7 (Update shared actions path)
=======
      - name: Prepare workflow
        uses: zowe-actions/shared-actions/prepare-workflow@main
>>>>>>> 8b5f64d (Debug nodejs setup action)
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: Install
        run: npm install --no-audit

      - name: Lint
        run: npm run lint

  run-code-ql:
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        # Initializes the CodeQL tools for scanning.
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v1
          with:
              languages: javascript

        # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
        # If this step fails, then you should remove it and run the build manually (see below)
        - name: Autobuild
          uses: github/codeql-action/autobuild@v1

        # ℹ️ Command-line programs to run using the OS shell.
        # 📚 https://git.io/JvXDl

        # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
        #    and modify them (or add more) to build your code if your project
        #    uses a compiled language

        #- run: |
        #   make bootstrap
        #   make release

        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v1

    