name: TEST1 target
on: 
  pull_request_target:
    types: [opened, synchronize]
  


jobs:
  test1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls

      - name: echo
        run: echo ">>>${{ secrets.NPM_PRIVATE_REGISTRY_EMAIL }}<<<"

